Repository devdaydresden/devday_website, pull requests merged in 2018-10, with the labels that each got.

#46 Add tests for management commands
  devday/devday/tests/test_management_commands_devdata.py
  devday/devday/tests/test_management_commands_useremails.py
  devday/devday/tests/test_utils_devdata.py
  devday/devday/tests/test_utils_words.py
  devday/devday/utils/devdata.py
Labels: django, enhancement

#47 Fix regression in ./prod.sh backup
  prod.sh
Labels: bug

#48 Show session grid to staff
  devday/devday/utils/devdata.py
  devday/talk/tests/test_views.py
  devday/talk/views.py
Labels: bug, django

#53 Add attendee checkin
  Pipfile
  Pipfile.lock
  devday/attendee/admin.py
  devday/attendee/cms_menus.py
  devday/attendee/forms.py
  devday/attendee/locale/de/LC_MESSAGES/django.po
  devday/attendee/migrations/0008_add_checkin.py
  devday/attendee/models.py
  devday/attendee/templates/attendee/checkin.html
  devday/attendee/templates/attendee/checkin_qrcode.html
  devday/attendee/templates/attendee/checkin_qrcode_include.html
  devday/attendee/templates/attendee/checkin_result.html
  devday/attendee/templates/attendee/cms_menus.py
  devday/attendee/templates/attendee/profile.html
  devday/attendee/tests/test_forms.py
  devday/attendee/tests/test_models.py
  devday/attendee/tests/test_views.py
  devday/attendee/views.py
  devday/devday/settings/base.py
  devday/devday/static/css/style.css.map
  devday/devday/static/js/main.js
  devday/devday/static/js/main.js.map
  devday/devday/static/js/main.min.js
  devday/devday/tests/__init__.py
  devday/devday/urls.py
  devday/devday/utils/devdata.py
  devday/event/migrations/0005_auto_20181010_2051.py
  devday/talk/tests/test_views.py
  docker/app/Dockerfile-dev
  frontend/gulp/config.js
  frontend/gulp/tasks/development/js.js
  frontend/package.json
  frontend/src/js/components/qrcodelinks.js
  frontend/yarn.lock
Labels: django, enhancement

#59 Unify prod and dev Dockerfile for fast image builds
  devday/devday/settings/base.py
  devday/devday/settings/dev.py
  devday/devday/settings/prod.py
  docker-compose.dev.yml
  docker/app/Dockerfile-dev
  docker/app/Dockerfile-prod
  docker/db/devday_db-prod.sql
  docker/revproxy/httpd.conf
  docker/vault/init_unseal_fill_vault.sh
Labels: build

#68 Add update command
  docker/vault/init_unseal_fill_vault.sh
  prod.sh
Labels: build

#82 Reorganize menus
  README-DEV.md
  devday/attendee/cms_menus.py
  devday/attendee/cms_toolbars.py
  devday/attendee/forms.py
  devday/attendee/locale/de/LC_MESSAGES/django.po
  devday/attendee/templates/attendee/attendee_register_success.html
  devday/attendee/templates/attendee/cms_menus.py
  devday/attendee/templates/attendee/login_or_register.html
  devday/devday/cms_menus.py
  devday/devday/cms_toolbars.py
  devday/devday/locale/de/LC_MESSAGES/django.po
  devday/devday/static/css/style.css
  devday/devday/static/fonts/fa-brands-400.eot
  devday/devday/static/fonts/fa-brands-400.svg
  devday/devday/static/fonts/fa-brands-400.ttf
  devday/devday/static/fonts/fa-brands-400.woff
  devday/devday/static/fonts/fa-brands-400.woff2
  devday/devday/static/fonts/fa-regular-400.eot
  devday/devday/static/fonts/fa-regular-400.svg
  devday/devday/static/fonts/fa-regular-400.ttf
  devday/devday/static/fonts/fa-regular-400.woff
  devday/devday/static/fonts/fa-regular-400.woff2
  devday/devday/static/fonts/fa-solid-900.eot
  devday/devday/static/fonts/fa-solid-900.svg
  devday/devday/static/fonts/fa-solid-900.ttf
  devday/devday/static/fonts/fa-solid-900.woff
  devday/devday/static/fonts/fa-solid-900.woff2
  devday/devday/templates/base_menu.html
  devday/devday/templates/menu/menu.html
  devday/devday/templates/menu/menu_title.html
  devday/devday/tests/test_cms_menus.py
  devday/devday/tests/test_utils_devdata.py
  devday/devday/tests/test_views.py
  devday/devday/urls.py
  devday/devday/utils/devdata.py
  devday/devday/utils/devday_toolbar.py
  devday/event/cms_menus.py
  devday/event/locale/de/LC_MESSAGES/django.po
  devday/speaker/locale/de/LC_MESSAGES/django.po
  devday/sponsoring/locale/de/LC_MESSAGES/django.po
  devday/talk/__init__.py
  devday/talk/apps.py
  devday/talk/locale/de/LC_MESSAGES/django.po
  devday/talk/tests/test_apps.py
  devday/talk/tests/test_context_processors.py
  devday/talk/tests/test_views.py
  devday/twitterfeed/locale/de/LC_MESSAGES/django.po
  frontend/gulp/config.js
  frontend/package.json
  frontend/src/scss/style.scss
  frontend/src/scss/variables.scss
  frontend/yarn.lock
  run.sh
Labels: django, frontend

#84 Added some visual enhancements
  devday/devday/static/css/style.css
  frontend/src/scss/components/sessiongrid.scss
  frontend/src/scss/components/sponsor-deck.scss
  frontend/src/scss/components/sponsor-form.scss
  frontend/src/scss/style.scss
  frontend/src/scss/variables.scss
Labels: enhancement, frontend
